### ISSUE TITLE
issue/stop on opening localhost

### ISSUE THREAD

**Issue by dizplayy** [Piero24/TelegramBot-AmazonOffers#13]
Hi!
as soon I try to open the localhost page i get this on prompt:
![image](https://github.com/user-attachments/assets/da77156d-1410-4c52-8018-0013bae52a8c)

log: 
`2024-12-11 11:46:31 :: [activity_inspector.py    ] - [run_server             ] - [INFO    ] - Start the server...
2024-12-11 11:46:31 :: [activity_inspector.py    ] - [run_server             ] - [INFO    ] - The server is running at localhost:8001.
2024-12-11 11:46:31 :: [list_manager.py          ] - [sub_of_raw_products    ] - [DEBUG   ] - Total number of category selected: 3
2024-12-11 11:46:31 :: [amz_paapi_sdk.py         ] - [search_items_by_kw     ] - [ERROR   ] - Error calling PA-API 5.0! - Status code: 429 - Request ID: 4ba061d9-399c-4a54-ac25-7ec4f72d1e79
2024-12-11 11:46:31 :: [amz_paapi_sdk.py         ] - [search_items_by_kw     ] - [ERROR   ] - Errors : {"__type":"com.amazon.paapi5#TooManyRequestsException","Errors":[{"Code":"TooManyRequests","Message":"The request was denied due to request throttling. Please verify the number of requests made per second to the Amazon Product Advertising API."}]}
2024-12-11 11:46:31 :: [time_scheduler.py        ] - [amz_wait_time          ] - [DEBUG   ] - Waiting 2 minutes for Status Code: 429.`

I tried to wait several mins between the runs, but same result.
Any hint?
ty

**Comment by Piero24** [comment]
Hi, This error indicates that the server is receiving malformed requests or data in a format it cannot interpret. The “illegible” data suggests that the client might be sending invalid or incorrectly encoded data.

#### Before Proceeding:
- I noticed you changed the port from **8000** to **8001**. Does the same issue occur when using port **8000** or other ports?
- If you already tried different ports and the issue persists, we need more information from the logs. Follow the steps below:

#### Steps to Debug the Issue:

Do the following changes to the file [src/web/activity_inspector.py](https://github.com/Piero24/TelegramBot-AmazonOffers/blob/main/src/web/activity_inspector.py#L35)

**1. Log the Incoming Request**
Modify the [do_GET](https://github.com/Piero24/TelegramBot-AmazonOffers/blob/6d56f82fbe9b75f319fa122f6cd75ca83b1e344c/src/web/activity_inspector.py#L43) function to log incoming requests with details about the path and headers:

```python3
def do_GET(self) -> None:
    logger.info(f"Request received: Path={self.path}, Headers={self.headers}")
    # ... 
```

**2. Log the Requested File Path**
Log the actual file path being requested and verify its existence in the [do_GET](https://github.com/Piero24/TelegramBot-AmazonOffers/blob/6d56f82fbe9b75f319fa122f6cd75ca83b1e344c/src/web/activity_inspector.py#L56) function:

```python3
# ... 
try:
    logger.info(f"Serving file: {file_path}")
    with open(file_path, 'rb') as file:
        content = file.read()
except FileNotFoundError:
    logger.error(f"File not found: {file_path}")
    self.send_error(404, "File not found")
    return
# ... 
```


**3. Capture Unhandled Requests**
Use the handle function to log raw requests and capture any unhandled errors [class SimpleHTTPRequestHandler(BaseHTTPRequestHandler)](https://github.com/Piero24/TelegramBot-AmazonOffers/blob/6d56f82fbe9b75f319fa122f6cd75ca83b1e344c/src/web/activity_inspector.py#L35):

```python3
def handle(self):
    try:
        logger.info(f"Raw request: {self.raw_requestline}")
        super().handle()
    except Exception as e:
        logger.error(f"Error handling request: {e}")
```


**4. Verify the Server is Listening on the Specified Port**
Ensure the server is actively listening on the specified port. Run the following command:
```bash
netstat -an | grep {settings.PORT}
```

**5. Check the URL Being Accessed**
If you’re using a browser to access localhost:8001, ensure you’re providing a valid URL. For example:
- Valid: http://localhost:8001/
- Invalid: Typos or incorrect port numbers.


#### Next Steps:
- Apply these changes and run the server.
- Share the logs or errors captured during the test.

Let me know the results so we can proceed with further troubleshooting!

**Comment by dizplayy** [comment]
Hi!
I had started with the default port 8000 but then changed it to 8001 to avoid possible interference with other apps that might share the port.

With the code implementations you mentioned I no longer get errors in the terminal (after ******************** Thank you! ******************** ) even when I try to open localhost.

This is the compelsive log after the run and the first call to localhost in the browser.


`2024-12-11 22:13:36 :: [activity_inspector.py    ] - [run_server             ] - [INFO    ] - Start the server...
2024-12-11 22:13:36 :: [activity_inspector.py    ] - [run_server             ] - [INFO    ] - The server is running at localhost:8001.
2024-12-11 22:13:36 :: [list_manager.py          ] - [sub_of_raw_products    ] - [DEBUG   ] - Total number of category selected: 3
2024-12-11 22:13:36 :: [amz_paapi_sdk.py         ] - [search_items_by_kw     ] - [ERROR   ] - Error calling PA-API 5.0! - Status code: 429 - Request ID: 96fa0a12-8353-45eb-8b50-3d40d0ebd9e6
2024-12-11 22:13:36 :: [amz_paapi_sdk.py         ] - [search_items_by_kw     ] - [ERROR   ] - Errors : {"__type":"com.amazon.paapi5#TooManyRequestsException","Errors":[{"Code":"TooManyRequests","Message":"The request was denied due to request throttling. Please verify the number of requests made per second to the Amazon Product Advertising API."}]}
2024-12-11 22:13:36 :: [time_scheduler.py        ] - [amz_wait_time          ] - [DEBUG   ] - Waiting 2 minutes for Status Code: 429.
2024-12-11 22:13:52 :: [activity_inspector.py    ] - [handle                 ] - [ERROR   ] - Error handling request: 'SimpleHTTPRequestHandler' object has no attribute 'raw_requestline'
2024-12-11 22:13:52 :: [activity_inspector.py    ] - [handle                 ] - [ERROR   ] - Error handling request: 'SimpleHTTPRequestHandler' object has no attribute 'raw_requestline'
2024-12-11 22:13:54 :: [activity_inspector.py    ] - [handle                 ] - [ERROR   ] - Error handling request: 'SimpleHTTPRequestHandler' object has no attribute 'raw_requestline'
2024-12-11 22:13:54 :: [activity_inspector.py    ] - [handle                 ] - [ERROR   ] - Error handling request: 'SimpleHTTPRequestHandler' object has no attribute 'raw_requestline'`

**Comment by Piero24** [comment]
Yes it has disappeared at the moment because we are trying to capture the error to understand where the problem is.
But can you log in now?

Anyway I made a mistake, **redo point 3 with the following code** and send me again the logs:

```python3
def handle(self):
    """Intercept and log raw HTTP requests."""
    try:
        logger.info(f"Request line: {self.requestline}")
        super().handle()
    except Exception as e:
        logger.error(f"Error handling request: {e}")
```

**Comment by dizplayy** [comment]
here's the new log. localhost still unreacheable ( localhost non ha inviato dati. ERR_EMPTY_RESPONSE )

`2024-12-12 10:55:26 :: [amz_paapi_sdk.py         ] - [search_items_by_kw     ] - [INFO    ] - API called Successfully. Category: Computers - Keyword: schede madri - Page: 3 - Min Saving Percent: Deactivated
2024-12-12 10:55:26 :: [amz_paapi_sdk.py         ] - [search_items_by_kw     ] - [DEBUG   ] - Products Found (8/8): ['B0BXFBN121', 'B0CZ1881BP', 'B0CSKH1NJF', 'B0BMM7NZDX', 'B08CKJB8P1', 'B0BJW1G7VN', 'B0BHHVLN34', 'B0BZD3BMZL']
2024-12-12 10:55:32 :: [activity_inspector.py    ] - [run_server             ] - [INFO    ] - Start the server...
2024-12-12 10:55:32 :: [activity_inspector.py    ] - [run_server             ] - [INFO    ] - The server is running at localhost:8001.
2024-12-12 10:55:32 :: [list_manager.py          ] - [sub_of_raw_products    ] - [DEBUG   ] - Total number of category selected: 3
2024-12-12 10:55:33 :: [activity_inspector.py    ] - [handle                 ] - [ERROR   ] - Error handling request: 'SimpleHTTPRequestHandler' object has no attribute 'raw_requestline'
2024-12-12 10:55:33 :: [activity_inspector.py    ] - [handle                 ] - [ERROR   ] - Error handling request: 'SimpleHTTPRequestHandler' object has no attribute 'raw_requestline'
2024-12-12 10:55:33 :: [amz_paapi_sdk.py         ] - [search_items_by_kw     ] - [INFO    ] - API called Successfully. Category: Electronics - Keyword: iPhone - Page: 1 - Min Saving Percent: Deactivated
2024-12-12 10:55:33 :: [amz_paapi_sdk.py         ] - [search_items_by_kw     ] - [DEBUG   ] - Products Found (8/8): ['B0CHWV5HTM', 'B09G995PVT', 'B0BDKBLF8C', 'B0DGJDQP2N', 'B0DGJMBTYK', 'B0DGJJFXWB', 'B0CHWV28JR', 'B0D17MV9V1']
`

**Comment by Piero24** [comment]
Did you modify the `def handle(self)` function as previously indicated? Because these logs still show issues related to the `def handle(self)` function that I pointed out at the beginning of the conversation.

[This one](https://github.com/Piero24/TelegramBot-AmazonOffers/issues/13#issuecomment-2538033677) is the correct one:

From the terminal, use the following commands and copy the responses:
```bash
curl http://localhost:8001/
curl http://localhost:8001/style.css
```

**Comment by dizplayy** [comment]
Sorry, maybe i took the wrong log.
here's the right one with handle updated:

`2024-12-12 18:49:00 :: [activity_inspector.py    ] - [run_server             ] - [INFO    ] - Start the server...
2024-12-12 18:49:00 :: [activity_inspector.py    ] - [run_server             ] - [INFO    ] - The server is running at localhost:8001.
2024-12-12 18:49:00 :: [list_manager.py          ] - [sub_of_raw_products    ] - [DEBUG   ] - Total number of category selected: 3
2024-12-12 18:49:01 :: [amz_paapi_sdk.py         ] - [search_items_by_kw     ] - [INFO    ] - API called Successfully. Category: Computers - Keyword: monitor gaming - Page: 1 - Min Saving Percent: Activated
2024-12-12 18:49:01 :: [amz_paapi_sdk.py         ] - [search_items_by_kw     ] - [DEBUG   ] - Products Found (8/8): ['B0D4QVTZ5Y', 'B0D4QYD65C', 'B0CP9L34CJ', 'B0CN6LTT2H', 'B0CNKCW5ZJ', 'B09RB7TP2V', 'B0CRVMR1W9', 'B0C8JTZLTV']
2024-12-12 18:49:04 :: [amz_paapi_sdk.py         ] - [search_items_by_kw     ] - [INFO    ] - API called Successfully. Category: Computers - Keyword: monitor gaming - Page: 2 - Min Saving Percent: Deactivated
2024-12-12 18:49:04 :: [amz_paapi_sdk.py         ] - [search_items_by_kw     ] - [DEBUG   ] - Products Found (8/8): ['B0CN6LTT2H', 'B0CP9L34CJ', 'B0CRVMR1W9', 'B0CNKCW5ZJ', 'B09RB7TP2V', 'B0CP9J29QY', 'B0CWXVTFTX', 'B0CM28TPBY']
2024-12-12 18:49:07 :: [amz_paapi_sdk.py         ] - [search_items_by_kw     ] - [INFO    ] - API called Successfully. Category: Computers - Keyword: monitor gaming - Page: 3 - Min Saving Percent: Deactivated
2024-12-12 18:49:07 :: [amz_paapi_sdk.py         ] - [search_items_by_kw     ] - [DEBUG   ] - Products Found (8/8): ['B0C8JTZLTV', 'B0CM28YH6K', 'B0C66CFZ6Q', 'B0C28SG29Q', 'B09YV1V12P', 'B0C28RM88F', 'B0CZ3RVSXB', 'B09XTRCCSS']
2024-12-12 18:49:10 :: [amz_paapi_sdk.py         ] - [search_items_by_kw     ] - [INFO    ] - API called Successfully. Category: Computers - Keyword: monitor - Page: 1 - Min Saving Percent: Deactivated
2024-12-12 18:49:10 :: [amz_paapi_sdk.py         ] - [search_items_by_kw     ] - [DEBUG   ] - Products Found (8/8): ['B0BVX5HSMP', 'B0BVWPS1H7', 'B0BT7TVX7S', 'B082LHJH3P', 'B0C28QX7DS', 'B0CPFSGV1Z', 'B0C8JTZLTV', 'B0BT4Y3Y4H']
2024-12-12 18:49:12 :: [amz_paapi_sdk.py         ] - [search_items_by_kw     ] - [INFO    ] - API called Successfully. Category: Computers - Keyword: monitor - Page: 2 - Min Saving Percent: Deactivated
2024-12-12 18:49:12 :: [amz_paapi_sdk.py         ] - [search_items_by_kw     ] - [DEBUG   ] - Products Found (8/8): ['B0CP7QLM3G', 'B06Y13QBYL', 'B0DCCBXQXJ', 'B0CX9CT3ZF', 'B08MQMWK82', 'B0BQWGGNBV', 'B0CZ3LQHKL', 'B0C66CFZ6Q']
2024-12-12 18:49:15 :: [amz_paapi_sdk.py         ] - [search_items_by_kw     ] - [INFO    ] - API called Successfully. Category: Computers - Keyword: monitor - Page: 3 - Min Saving Percent: Activated
2024-12-12 18:49:15 :: [amz_paapi_sdk.py         ] - [search_items_by_kw     ] - [DEBUG   ] - Products Found (8/8): ['B0B725W6QP', 'B0CP9L34CJ', 'B09ZQTZ25D', 'B0B8JYKB44', 'B0CNKCW5ZJ', 'B09RB7TP2V', 'B0D4C256NR', 'B0CRVMR1W9']
2024-12-12 18:49:18 :: [amz_paapi_sdk.py         ] - [search_items_by_kw     ] - [INFO    ] - API called Successfully. Category: Computers - Keyword: monitor - Page: 1 - Min Saving Percent: Deactivated
2024-12-12 18:49:18 :: [amz_paapi_sdk.py         ] - [search_items_by_kw     ] - [DEBUG   ] - Products Found (8/8): ['B0BVX5HSMP', 'B0BVWPS1H7', 'B0BT7TVX7S', 'B082LHJH3P', 'B0C28QX7DS', 'B0CPFSGV1Z', 'B0C8JTZLTV', 'B0BT4Y3Y4H']
2024-12-12 18:49:20 :: [amz_paapi_sdk.py         ] - [search_items_by_kw     ] - [INFO    ] - API called Successfully. Category: Computers - Keyword: monitor - Page: 2 - Min Saving Percent: Activated
2024-12-12 18:49:20 :: [amz_paapi_sdk.py         ] - [search_items_by_kw     ] - [DEBUG   ] - Products Found (8/8): ['B0C66CFZ6Q', 'B0BQWGGNBV', 'B0BYMR3XM7', 'B0BFWSHXYY', 'B0DD1861XK', 'B0D4QVTZ5Y', 'B0BQWD2KD6', 'B09G6TX7L5']
2024-12-12 18:49:23 :: [amz_paapi_sdk.py         ] - [search_items_by_kw     ] - [INFO    ] - API called Successfully. Category: Computers - Keyword: monitor - Page: 3 - Min Saving Percent: Deactivated
2024-12-12 18:49:23 :: [amz_paapi_sdk.py         ] - [search_items_by_kw     ] - [DEBUG   ] - Products Found (8/8): ['B0CX9CVS9Q', 'B0CZ3NW9PL', 'B0BYMR3XM7', 'B0845NMZ6K', 'B0BFWSHXYY', 'B0C6DDGYZ4', 'B0957LFHTM', 'B0CRNHMCMQ']
2024-12-12 18:49:26 :: [activity_inspector.py    ] - [handle                 ] - [ERROR   ] - Error handling request: 'SimpleHTTPRequestHandler' object has no attribute 'requestline'
2024-12-12 18:49:26 :: [activity_inspector.py    ] - [handle                 ] - [ERROR   ] - Error handling request: 'SimpleHTTPRequestHandler' object has no attribute 'requestline'
2024-12-12 18:49:26 :: [amz_paapi_sdk.py         ] - [search_items_by_kw     ] - [INFO    ] - API called Successfully. Category: Computers - Keyword: computer da gaming portatili - Page: 1 - Min Saving Percent: Deactivated
2024-12-12 18:49:26 :: [amz_paapi_sdk.py         ] - [search_items_by_kw     ] - [DEBUG   ] - Products Found (8/8): ['B0CGDJ67QR', 'B0D9B9VH47', 'B0D8WF5RHR', 'B0D5RGLWZL', 'B0CXY4MT8Q', 'B0D5B6BR23', 'B0D8VM8NTF', 'B0D66M83HD']
2024-12-12 18:49:27 :: [activity_inspector.py    ] - [handle                 ] - [ERROR   ] - Error handling request: 'SimpleHTTPRequestHandler' object has no attribute 'requestline'
2024-12-12 18:49:27 :: [activity_inspector.py    ] - [handle                 ] - [ERROR   ] - Error handling request: 'SimpleHTTPRequestHandler' object has no attribute 'requestline'
2024-12-12 18:49:29 :: [amz_paapi_sdk.py         ] - [search_items_by_kw     ] - [INFO    ] - API called Successfully. Category: Computers - Keyword: computer da gaming portatili - Page: 2 - Min Saving Percent: Deactivated
2024-12-12 18:49:29 :: [amz_paapi_sdk.py         ] - [search_items_by_kw     ] - [DEBUG   ] - Products Found (8/8): ['B0CWNPRVDP', 'B0D8WDM4FZ', 'B0CQ2QR1WP', 'B0DFPNXC4P', 'B0C4V9GYVG', 'B0DNYYRF1W', 'B0BZVW5XRF', 'B0CQ2PZDQK']
`

Here's the curl:
![image](https://github.com/user-attachments/assets/74a7c3ad-fdd4-4246-a86f-db9d7f61bca2)

**Comment by Piero24** [comment]
That’s very strange.
Did you install all the dependencies listed in the `requirements.txt` file? Did you update them, or did you stick to the specified versions in the file?
Also, which version of Python are you using? If you’re using a version that’s too recent, try switching to `Python 3.9`.

Also try this and tell if it's all ok:
Start Python’s built-in HTTP server, follow these steps:
1. Change the file [src/web/activity_inspector.py](https://github.com/Piero24/TelegramBot-AmazonOffers/blob/main/src/web/activity_inspector.py#L35) with a new one without any change... 
2. Open Terminal
3. Go to your files’ folder. Use the cd command to navigate to the folder with the files you want to serve. For example:
    ```bash
    cd /path/to/your/files
    ```
4.	Start the server. Run this command:
    ```bash
    python -m http.server 8001
    ```
    This starts a server on port 8001. If you don’t specify a port, it defaults to 8000.

5.	Access the server:
Open your browser and go to: http://localhost:8001
You should see the files listed.

**Comment by Marcod83** [comment]
Ciao Pietro 
ho avviato l'applicativo ma non riesco ad accedere alla pagina web. nel prompt ricevo questi messaggi , puoi darmi una mano a risolvere ? 
Subscribe to WebOfferte Channel: https://linktr.ee/webofferte to support the development!


 ********************   Thank you!   ********************


127.0.0.1 - - [28/Feb/2025 13:08:59] code 404, message File not found
127.0.0.1 - - [28/Feb/2025 13:08:59] "GET /index.html HTTP/1.1" 404 -
127.0.0.1 - - [28/Feb/2025 13:08:59] code 404, message File not found
127.0.0.1 - - [28/Feb/2025 13:08:59] "GET /favicon.ico HTTP/1.1" 404 -
127.0.0.1 - - [28/Feb/2025 13:09:07] code 404, message File not found
127.0.0.1 - - [28/Feb/2025 13:09:07] "GET / HTTP/1.1" 404 -
127.0.0.1 - - [28/Feb/2025 13:09:09] code 404, message File not found
127.0.0.1 - - [28/Feb/2025 13:09:09] "GET / HTTP/1.1" 404 -
127.0.0.1 - - [28/Feb/2025 13:09:10] code 404, message File not found
127.0.0.1 - - [28/Feb/2025 13:09:10] "GET / HTTP/1.1" 404 -
127.0.0.1 - - [28/Feb/2025 13:09:10] code 404, message File not found
127.0.0.1 - - [28/Feb/2025 13:09:10] "GET / HTTP/1.1" 404 -
127.0.0.1 - - [28/Feb/2025 13:09:10] code 404, message File not found
127.0.0.1 - - [28/Feb/2025 13:09:10] "GET / HTTP/1.1" 404 -
127.0.0.1 - - [28/Feb/2025 13:09:10] code 404, message File not found
127.0.0.1 - - [28/Feb/2025 13:09:10] "GET / HTTP/1.1" 404 -
----------------------------------------
Exception occurred during processing of request from ('127.0.0.1', 50807)
Traceback (most recent call last):
  File "C:\TelegramBot-AmazonOffers-main\src\web\activity_inspector.py", line 57, in do_GET
    with open(file_path, 'rb') as file:
         ^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'src/web/index.html'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ced\AppData\Local\Programs\Python\Python312\Lib\socketserver.py", line 318, in _handle_request_noblock
    self.process_request(request, client_address)
  File "C:\Users\ced\AppData\Local\Programs\Python\Python312\Lib\socketserver.py", line 349, in process_request
    self.finish_request(request, client_address)
  File "C:\Users\ced\AppData\Local\Programs\Python\Python312\Lib\socketserver.py", line 362, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "C:\Users\ced\AppData\Local\Programs\Python\Python312\Lib\socketserver.py", line 761, in __init__
    self.handle()
  File "C:\Users\ced\AppData\Local\Programs\Python\Python312\Lib\http\server.py", line 436, in handle
    self.handle_one_request()
  File "C:\Users\ced\AppData\Local\Programs\Python\Python312\Lib\http\server.py", line 424, in handle_one_request
    method()
  File "C:\TelegramBot-AmazonOffers-main\src\web\activity_inspector.py", line 61, in do_GET
    self.send_error(404, "File not found")
  File "C:\Users\ced\AppData\Local\Programs\Python\Python312\Lib\http\server.py", line 491, in send_error
    self.wfile.write(body)
  File "C:\Users\ced\AppData\Local\Programs\Python\Python312\Lib\socketserver.py", line 840, in write
    self._sock.sendall(b)
ConnectionAbortedError: [WinError 10053] Connessione interrotta dal software del computer host
----------------------------------------
127.0.0.1 - - [28/Feb/2025 13:12:18] code 404, message File not found
127.0.0.1 - - [28/Feb/2025 13:12:18] "GET / HTTP/1.1" 404 -
